# Generated by Django 4.0.5 on 2022-09-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movienight',
            name='start_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
